### ISSUE TITLE
Diff json files

### ISSUE THREAD

**Issue by shawninder** [vigour-io/git-spy#3]
If the need arises to diff JSON files (to know if the interesting part of the file changed)
- Get file before
- Get file after
- Feed both through oboe, getting the fields you're watching, dropping the rest
- Run a diff on these subsections of the file (the watched fields)

**Comment by shawninder** [comment]
This will be handled by users of git-spy

**Comment by shawninder** [comment]
I did some of it but there might be some left to do

**Comment by andrepadez** [comment]
thanks a lot @shawninder
